<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>kosa-mini-project</artifactId>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
              <version>${lombok.version}</version>
            </path>
          </annotationProcessorPaths>
          <release>11</release>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.13.0</version>
      </plugin>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <configuration>
          <failOnMissingWebXml>false</failOnMissingWebXml>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.4.0</version>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <artifactId>junit</artifactId>
      <groupId>junit</groupId>
      <scope>test</scope>
      <version>3.8.1</version>
    </dependency>
    <!-- Spring -->
    <dependency>
      <artifactId>spring-context</artifactId>
      <groupId>org.springframework</groupId>
      <version>${spring.version}</version>
    </dependency>

    <dependency>
      <artifactId>spring-jdbc</artifactId>
      <groupId>org.springframework</groupId>
      <version>${spring.version}</version>
    </dependency>

    <dependency>
      <artifactId>spring-tx</artifactId>
      <groupId>org.springframework</groupId>
      <version>${spring.version}</version>
    </dependency>

    <dependency>
      <artifactId>spring-webmvc</artifactId>
      <groupId>org.springframework</groupId>
      <version>${spring.version}</version>
    </dependency>

    <dependency>
      <artifactId>jackson-databind</artifactId>
      <groupId>com.fasterxml.jackson.core</groupId>
      <version>${jackson.version}</version>
    </dependency>

    <!-- MyBatis -->
    <dependency>
      <artifactId>mybatis</artifactId>
      <groupId>org.mybatis</groupId>
      <version>${mybatis.version}</version>
    </dependency>

    <dependency>
      <artifactId>mybatis-spring</artifactId>
      <groupId>org.mybatis</groupId>
      <version>${mybatis.spring.version}</version>
    </dependency>

    <!-- Lombok -->
    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <scope>provided</scope>
      <version>${lombok.version}</version>
    </dependency>

    <!-- Oracle -->
    <dependency>
      <artifactId>ojdbc11</artifactId>
      <groupId>com.oracle.database.jdbc</groupId>
      <version>${oracle.jdbc.version}</version>
    </dependency>

    <!-- Servlet API -->
    <dependency>
      <artifactId>javax.servlet-api</artifactId>
      <groupId>javax.servlet</groupId>
      <scope>provided</scope>
      <version>${javax.servlet.version}</version>
    </dependency>
  </dependencies>
  <groupId>futurenet.fullstack</groupId>
  <modelVersion>4.0.0</modelVersion>

  <name>kosa-mini-project</name>
  <packaging>war</packaging>

  <properties>
    <jackson.version>2.17.2</jackson.version>
    <javax.servlet.version>4.0.1</javax.servlet.version>
    <lombok.version>1.18.46</lombok.version>

    <maven.compiler.release>11</maven.compiler.release>
    <mybatis.spring.version>2.1.2</mybatis.spring.version>
    <mybatis.version>3.5.19</mybatis.version>

    <oracle.jdbc.version>23.8.0.25.04</oracle.jdbc.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <spring.version>5.3.39</spring.version>
  </properties>

  <url>http://maven.apache.org</url>

  <version>1.0-SNAPSHOT</version>
</project>
