server:
  port: ${AUTH_SERVICE_PORT:8081}

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${ORACLE_DB_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
    username: ${ORACLE_DB_USERNAME:mail_app}
    password: ${ORACLE_DB_PASSWORD:mail_app}

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

reservation-service:
  reservations-url: ${RESERVATION_SERVICE_RESERVATIONS_URL:http://localhost:8082/reservations}
